services:
  - type: web
    name: spyonspy
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRADIER_TOKEN
        sync: false
